services:
  x-bft: &bft-base
    platform: linux/amd64
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    # https://github.com/unicitynetwork/bft-core/pkgs/container/bft-core
    image: ghcr.io/unicitynetwork/bft-core:49d48f8fd3686aff1066d98eff2512e5fc71713c
  bft-root:
    <<: *bft-base
    volumes:
      - ./data/genesis-root:/genesis/root
      - ./data/genesis:/genesis
    healthcheck:
      test: ["CMD", "nc", "-zv", "bft-root", "8000"]
      interval: 5s
    networks:
      - default
    entrypoint: ["/busybox/sh", "-c"]
    command:
      - |
        if [ -f /genesis/root/node-info.json ] && [ -f /genesis/trust-base.json ] && [ -f /genesis/root/trust-base-signed.json ]; then
          echo "Genesis files already exist, skipping initialization."
        else
          echo "Creating root genesis..." &&
          ubft root-node init --home /genesis/root -g &&
          echo "Creating root trust base..." &&
          ubft trust-base generate --home /genesis --network-id 3 --node-info /genesis/root/node-info.json &&
          echo "Signing root trust base..." &&
          ubft trust-base sign --home /genesis/root --trust-base /genesis/trust-base.json
        fi
        echo "Starting root node..." &&
        ubft root-node run --home /genesis/root --address "/ip4/$(hostname -i)/tcp/8000" --trust-base /genesis/trust-base.json --rpc-server-address "$(hostname -i):8002" &&
        ls -l /genesis/root
        echo "Root node started successfully."

  bft-aggregator-genesis-gen:
    <<: *bft-base
    volumes:
      - ./data/genesis-root:/genesis/root
      - ./data/genesis:/genesis
    depends_on:
      bft-root:
        condition: service_healthy
    ports:
      - "11003:11003"
    networks:
      - default
    entrypoint: ["/busybox/sh", "-c"]
    command:
      - |
        if [ -f /genesis/aggregator/node-info.json ] && [ -f /genesis/shard-conf-7_0.json ]; then
          echo "Aggregator genesis and config already exist, skipping initialization."
        else
          echo "Creating aggregator genesis..." &&
          ubft shard-node init --home /genesis/aggregator --generate &&
          echo "Creating aggregator partition configuration..." &&
          ubft shard-conf generate --home /genesis --t2-timeout 5000 --network-id 3 --partition-id 7 --partition-type-id 7 --epoch-start 10 --node-info=/genesis/aggregator/node-info.json &&
          echo "Creating aggregator partition state..." &&
          ubft shard-conf genesis --home "/genesis/aggregator" --shard-conf /genesis/shard-conf-7_0.json
        fi
        chmod -R 755 /genesis/aggregator
        chmod 644 /genesis/shard-conf-7_0.json
        chmod 644 /genesis/trust-base.json
        chmod -R 755 /genesis/root
        echo "Permissions fixed."
        ls -l /genesis/aggregator &&
        ls -l /genesis/

  upload-configurations:
    image: curlimages/curl:8.13.0
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    depends_on:
      bft-root:
        condition: service_healthy
      bft-aggregator-genesis-gen:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - ./data/genesis:/genesis
    command: |
      /bin/sh -c "
        echo Uploading aggregator configuration &&
        curl -X PUT -H 'Content-Type: application/json' -d @/genesis/shard-conf-7_0.json http://bft-root:8002/api/v1/configurations
      "

  redis:
    image: redis:7-alpine
    container_name: aggregator-redis
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./data/redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongo1:
    image: mongo:7.0
    container_name: mongo-1
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./data/mongodb_data/mongo1:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 1s
      retries: 30

  mongo2:
    image: mongo:7.0
    container_name: mongo-2
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./data/mongodb_data/mongo2:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 1s
      retries: 30

  mongo3:
    image: mongo:7.0
    container_name: mongo-3
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./data/mongodb_data/mongo3:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 1s
      retries: 30

  mongo-setup:
    image: mongo:7.0
    container_name: mongo-setup
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    networks:
      - default
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    entrypoint:
      [
        "mongosh",
        "--host",
        "mongo1:27017",
        "--eval",
        "try { rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo1:27017'}, {_id: 1, host: 'mongo2:27017'}, {_id: 2, host: 'mongo3:27017'}]}) } catch(e) { print('Replica set already initialized or error:', e.message) }",
      ]

  # HAProxy load balancer for aggregators
  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8404:8404" # HAProxy stats page
    networks:
      - default
    volumes:
      - ./scripts/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      aggregator-1:
        condition: service_healthy
      aggregator-2:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:8404/stats",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  aggregator-1: &aggregator-base
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: aggregator-1
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - default
    volumes:
      - ./data/genesis:/app/bft-config
    environment: &environment-base # Server Configuration
      PORT: "3001"
      HOST: "0.0.0.0"
      CONCURRENCY_LIMIT: "1000"
      ENABLE_DOCS: "true"
      ENABLE_CORS: "true"

      # Database Configuration
      MONGODB_URI: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/aggregator?replicaSet=rs0"
      MONGODB_DATABASE: "aggregator"
      MONGODB_CONNECT_TIMEOUT: "10s"
      MONGODB_SERVER_SELECTION_TIMEOUT: "5s"

      # Redis Configuration
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      REDIS_POOL_SIZE: "100"
      REDIS_MIN_IDLE_CONNS: "10"

      # Storage Configuration
      USE_REDIS_FOR_COMMITMENTS: "true"
      REDIS_FLUSH_INTERVAL: "50ms"
      REDIS_MAX_BATCH_SIZE: "2000"

      # High Availability Configuration
      DISABLE_HIGH_AVAILABILITY: "false"
      LOCK_TTL_SECONDS: "30"
      LEADER_HEARTBEAT_INTERVAL: "10s"
      LEADER_ELECTION_POLLING_INTERVAL: "5s"

      # Logging Configuration
      LOG_LEVEL: "debug"
      LOG_FORMAT: "json"
      LOG_ENABLE_JSON: "true"

      # Processing Configuration
      BATCH_LIMIT: "1000"
      MAX_COMMITMENTS_PER_ROUND: "10000"

      # BFT Configuration
      # Enable BFT support and specify configuration file paths
      BFT_ENABLED: "true"
      BFT_KEY_CONF_FILE: "/app/bft-config/aggregator/keys.json"
      BFT_SHARD_CONF_FILE: "/app/bft-config/shard-conf-7_0.json"
      BFT_TRUST_BASE_FILES: "/app/bft-config/trust-base.json"
      # BFT_BOOTSTRAP_ADDRESSES will be set dynamically by the entrypoint script
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Extract the first root node's nodeId from trust-base.json
        if [ -f /app/bft-config/trust-base.json ]; then
          ROOT_NODE_ID=$$(cat /app/bft-config/trust-base.json | grep -o '"nodeId": "[^"]*"' | head -1 | cut -d'"' -f4)
          if [ -n "$$ROOT_NODE_ID" ]; then
            export BFT_BOOTSTRAP_ADDRESSES="/dns4/bft-root/tcp/8000/p2p/$$ROOT_NODE_ID"
            echo "Set BFT_BOOTSTRAP_ADDRESSES to: $$BFT_BOOTSTRAP_ADDRESSES"
          else
            echo "Warning: Could not extract nodeId from trust-base.json"
            exit 1
          fi
        else
          echo "Error: trust-base.json not found at /app/bft-config/trust-base.json"
          exit 1
        fi

        # Start the aggregator application
        exec /app/aggregator

    depends_on:
      bft-aggregator-genesis-gen:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      mongo-setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w2 127.0.0.1 $${PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  aggregator-2:
    <<: *aggregator-base
    container_name: aggregator-2
    ports:
      - "3002:3002"
    environment:
      <<: *environment-base
      PORT: "3002"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w2 127.0.0.1 $${PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
