services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: logging-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8088:8080
    environment:
      # Configure base path for reverse proxy routing
      # When accessed via HAProxy at /logs, Dozzle will generate correct asset URLs
      - DOZZLE_BASE=/logs
    restart: unless-stopped
