services:
  x-bft:
    &bft-base
    platform: linux/amd64
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    # https://github.com/unicitynetwork/bft-core/pkgs/container/bft-core
    image: ghcr.io/unicitynetwork/bft-core:ff28a5da20d4eb3f664264a136303a4e79a88e4c
  bft-root:
    <<: *bft-base
    volumes:
      - ./data/genesis-root:/genesis/root
      - ./data/genesis:/genesis
    healthcheck:
      test: [ "CMD", "nc", "-zv", "bft-root", "8000" ]
      interval: 5s
    networks:
      - default
    entrypoint: ["/busybox/sh", "-c"]
    command:
      - |
        if [ -f /genesis/root/node-info.json ] && [ -f /genesis/trust-base.json ] && [ -f /genesis/root/trust-base-signed.json ]; then
          echo "Genesis files already exist, skipping initialization."
        else
          echo "Creating root genesis..." &&
          ubft root-node init --home /genesis/root -g &&
          echo "Creating root trust base..." &&
          ubft trust-base generate --home /genesis --network-id 3 --node-info /genesis/root/node-info.json &&
          echo "Signing root trust base..." &&
          ubft trust-base sign --home /genesis/root --trust-base /genesis/trust-base.json
        fi
        echo "Starting root node..." &&
        ubft root-node run --home /genesis/root --address "/ip4/$(hostname -i)/tcp/8000" --trust-base /genesis/trust-base.json --rpc-server-address "$(hostname -i):8002" &&
        ls -l /genesis/root
        echo "Root node started successfully."

  bft-aggregator-genesis-gen:
    <<: *bft-base
    volumes:
      - ./data/genesis-root:/genesis/root
      - ./data/genesis:/genesis
    depends_on:
      bft-root:
        condition: service_healthy
    ports:
      - "11003:11003"
    networks:
      - default
    entrypoint: ["/busybox/sh", "-c"]
    command:
      - |
        if [ -f /genesis/aggregator/node-info.json ] && [ -f /genesis/shard-conf-7_0.json ]; then
          echo "Aggregator genesis and config already exist, skipping initialization."
        else
          echo "Creating aggregator genesis..." &&
          ubft shard-node init --home /genesis/aggregator --generate &&
          echo "Creating aggregator partition configuration..." &&
          ubft shard-conf generate --home /genesis --t2-timeout 5000 --network-id 3 --partition-id 7 --partition-type-id 7 --epoch-start 10 --node-info=/genesis/aggregator/node-info.json &&
          echo "Creating aggregator partition state..." &&
          ubft shard-conf genesis --home "/genesis/aggregator" --shard-conf /genesis/shard-conf-7_0.json
        fi
        chmod -R 755 /genesis/aggregator
        chmod 644 /genesis/shard-conf-7_0.json
        chmod 644 /genesis/trust-base.json
        chmod -R 755 /genesis/root
        echo "Permissions fixed."
        ls -l /genesis/aggregator &&
        ls -l /genesis/

  upload-configurations:
    image: curlimages/curl:8.13.0
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    depends_on:
      bft-root:
        condition: service_healthy
      bft-aggregator-genesis-gen:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - ./data/genesis:/genesis
    command: |
      /bin/sh -c "
        echo Uploading aggregator configuration &&
        curl -X PUT -H 'Content-Type: application/json' -d @/genesis/shard-conf-7_0.json http://bft-root:8002/api/v1/configurations
      "

  mongodb-shard1:
    image: mongo:7.0
    container_name: aggregator-shard1-mongodb
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - ./data/mongodb_shard1_data:/data/db
    command: ["--replSet", "rs-shard1", "--bind_ip_all", "--noauth"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs-shard1',members:[{_id:0,host:'mongodb-shard1:27017'}]}) }"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  mongodb-shard2:
    image: mongo:7.0
    container_name: aggregator-shard2-mongodb
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - ./data/mongodb_shard2_data:/data/db
    command: ["--replSet", "rs-shard2", "--bind_ip_all", "--noauth"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs-shard2',members:[{_id:0,host:'mongodb-shard2:27017'}]}) }"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis-shared:
    image: redis:7-alpine
    container_name: aggregator-redis-shared
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - ./data/redis_shared_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb-root:
    image: mongo:7.0
    container_name: aggregator-root-mongodb
    user: "${USER_UID:-1001}:${USER_GID:-1001}"
    restart: unless-stopped
    ports:
      - "27019:27017"
    networks:
      - default
    volumes:
      - ./data/mongodb_root_data:/data/db
    command: ["--replSet", "rs-root", "--bind_ip_all", "--noauth"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs-root',members:[{_id:0,host:'mongodb-root:27017'}]}) }"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  aggregator-shard1: &aggregator-base
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aggregator-shard1
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - default
    volumes:
      - ./data/genesis:/app/bft-config
      - ./certs:/app/certs:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment: &environment-base
      # Server Configuration
      PORT: "3000"
      HOST: "0.0.0.0"
      CONCURRENCY_LIMIT: "5000"
      ENABLE_DOCS: "true"
      ENABLE_CORS: "true"
      ENABLE_TLS: "false"
      TLS_CERT_FILE: "/app/certs/cert.pem"
      TLS_KEY_FILE: "/app/certs/key.pem"

      # Database Configuration
      MONGODB_URI: "mongodb://mongodb-shard1:27017/aggregator?replicaSet=rs-shard1&directConnection=true"
      MONGODB_DATABASE: "aggregator"
      MONGODB_CONNECT_TIMEOUT: "10s"
      MONGODB_SERVER_SELECTION_TIMEOUT: "5s"

      # High Availability Configuration
      DISABLE_HIGH_AVAILABILITY: "true"
      LOCK_TTL_SECONDS: "30"
      LEADER_HEARTBEAT_INTERVAL: "10s"
      LEADER_ELECTION_POLLING_INTERVAL: "5s"

      # Logging Configuration
      LOG_LEVEL: "debug"
      LOG_FORMAT: "json"
      LOG_ENABLE_JSON: "true"

      # Processing Configuration
      BATCH_LIMIT: "1000"
      COLLECT_PHASE_DURATION: "500ms"

      # BFT Configuration
      # Enable BFT support and specify configuration file paths
      BFT_ENABLED: "true"
      BFT_KEY_CONF_FILE: "/app/bft-config/aggregator/keys.json"
      BFT_SHARD_CONF_FILE: "/app/bft-config/shard-conf-7_0.json"
      BFT_TRUST_BASE_FILE: "/app/bft-config/trust-base.json"
      # BFT_BOOTSTRAP_ADDRESSES will be set dynamically by the entrypoint script

      # Redis Configuration
      REDIS_HOST: "redis-shared"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      REDIS_POOL_SIZE: "100"
      REDIS_MIN_IDLE_CONNS: "10"

      # Storage Configuration
      USE_REDIS_FOR_COMMITMENTS: "true"
      REDIS_STREAM_NAME: "commitments:shard:1"
      REDIS_FLUSH_INTERVAL: "50ms"
      REDIS_MAX_BATCH_SIZE: "2000"

      # Sharding configuration
      SHARDING_MODE: "child"
      SHARD_ID_LENGTH: 1
      SHARDING_CHILD_PARENT_RPC_ADDR: http://aggregator-root:3000
      SHARDING_CHILD_SHARD_ID: 3 # 0b11
      SHARDING_CHILD_ROUND_DURATION: 1s
      SHARDING_CHILD_PARENT_POLL_TIMEOUT: 5s
      SHARDING_CHILD_PARENT_POLL_INTERVAL: 100ms
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Extract the first root node's nodeId from trust-base.json
        if [ -f /app/bft-config/trust-base.json ]; then
          ROOT_NODE_ID=$$(cat /app/bft-config/trust-base.json | grep -o '"nodeId": "[^"]*"' | head -1 | cut -d'"' -f4)
          if [ -n "$$ROOT_NODE_ID" ]; then
            export BFT_BOOTSTRAP_ADDRESSES="/dns4/bft-root/tcp/8000/p2p/$$ROOT_NODE_ID"
            echo "Set BFT_BOOTSTRAP_ADDRESSES to: $$BFT_BOOTSTRAP_ADDRESSES"
          else
            echo "Warning: Could not extract nodeId from trust-base.json"
            exit 1
          fi
        else
          echo "Error: trust-base.json not found at /app/bft-config/trust-base.json"
          exit 1
        fi
        
        # Start the aggregator application
        exec /app/aggregator

    depends_on:
      upload-configurations:
        condition: service_completed_successfully
      mongodb-shard1:
        condition: service_healthy
      redis-shared:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
  aggregator-shard2:
    <<: *aggregator-base
    container_name: aggregator-shard2
    ports:
      - "3002:3000"
    environment:
      <<: *environment-base
      MONGODB_URI: "mongodb://mongodb-shard2:27017/aggregator?replicaSet=rs-shard2&directConnection=true"
      SHARDING_CHILD_SHARD_ID: 2 # 0b10
      REDIS_STREAM_NAME: "commitments:shard:2"
    depends_on:
      upload-configurations:
        condition: service_completed_successfully
      mongodb-shard2:
        condition: service_healthy
      redis-shared:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
  aggregator-root:
    <<: *aggregator-base
    container_name: aggregator-root
    ports:
      - "3009:3000"
    environment:
      <<: *environment-base
      MONGODB_URI: "mongodb://mongodb-root:27017/aggregator?replicaSet=rs-root&directConnection=true"
      SHARDING_MODE: "parent"
      BFT_ENABLED: "true"
      ENABLE_TLS: "false"
    depends_on:
      upload-configurations:
        condition: service_completed_successfully
      mongodb-root:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  default:
